# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build with a specific pipeline version

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    # failOnThreshold: moderate
    variableGroupName: ffc-pay-gateway-env-var
    pr_params:
      sftpManagedGatewayEnabled: $(pr_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(pr_sftpTraderEnabled)
      sfiEnabled: $(pr_sfiEnabled)
      sfiPilotEnabled: $(pr_sfiPilotEnabled)
      lumpSumsEnabled: $(pr_lumpSumsEnabled)
      csEnabled: $(pr_csEnabled)
      bpsEnabled: $(pr_bpsEnabled)
      esEnabled: $(pr_esEnabled)
      fcEnabled: $(pr_fcEnabled)
      impsEnabled: $(pr_impsEnabled)
      sfi23Enabled: $(pr_sfi23Enabled)
      dpsEnabled: $(pr_dpsEnabled)
      delinkedEnabled: $(pr_delinkedEnabled)
      combinedOfferEnabled: $(pr_combinedOfferEnabled)
      cohtCapitalEnabled: $(pr_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(pr_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(pr_sftpManagedGatewayUsername)
      sftpTraderHost: $(pr_sftpTraderHost)
      sftpTraderUsername: $(pr_sftpTraderUsername)
    snd2_params:
      sftpManagedGatewayEnabled: $(snd2_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(snd2_sftpTraderEnabled)
      sfiEnabled: $(snd2_sfiEnabled)
      sfiPilotEnabled: $(snd2_sfiPilotEnabled)
      lumpSumsEnabled: $(snd2_lumpSumsEnabled)
      csEnabled: $(snd2_csEnabled)
      bpsEnabled: $(snd2_bpsEnabled)
      esEnabled: $(snd2_esEnabled)
      fcEnabled: $(snd2_fcEnabled)
      impsEnabled: $(snd2_impsEnabled)
      sfi23Enabled: $(snd2_sfi23Enabled)
      dpsEnabled: $(snd2_dpsEnabled)
      delinkedEnabled: $(snd2_delinkedEnabled)
      combinedOfferEnabled: $(snd2_combinedOfferEnabled)
      cohtCapitalEnabled: $(snd2_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(snd2_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(snd2_sftpManagedGatewayUsername)
      sftpTraderHost: $(snd2_sftpTraderHost)
      sftpTraderUsername: $(snd2_sftpTraderUsername)
    dev_params:
      sftpManagedGatewayEnabled: $(dev_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(dev_sftpTraderEnabled)
      sfiEnabled: $(dev_sfiEnabled)
      sfiPilotEnabled: $(dev_sfiPilotEnabled)
      lumpSumsEnabled: $(dev_lumpSumsEnabled)
      csEnabled: $(dev_csEnabled)
      bpsEnabled: $(dev_bpsEnabled)
      esEnabled: $(dev_esEnabled)
      fcEnabled: $(dev_fcEnabled)
      impsEnabled: $(dev_impsEnabled)
      sfi23Enabled: $(dev_sfi23Enabled)
      dpsEnabled: $(dev_dpsEnabled)
      delinkedEnabled: $(dev_delinkedEnabled)
      combinedOfferEnabled: $(dev_combinedOfferEnabled)
      cohtCapitalEnabled: $(dev_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(dev_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(dev_sftpManagedGatewayUsername)
      sftpTraderHost: $(dev_sftpTraderHost)
      sftpTraderUsername: $(dev_sftpTraderUsername)
    test_params:
      sftpManagedGatewayEnabled: $(test_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(test_sftpTraderEnabled)
      sfiEnabled: $(test_sfiEnabled)
      sfiPilotEnabled: $(test_sfiPilotEnabled)
      lumpSumsEnabled: $(test_lumpSumsEnabled)
      csEnabled: $(test_csEnabled)
      bpsEnabled: $(test_bpsEnabled)
      esEnabled: $(test_esEnabled)
      fcEnabled: $(test_fcEnabled)
      impsEnabled: $(test_impsEnabled)
      sfi23Enabled: $(test_sfi23Enabled)
      dpsEnabled: $(test_dpsEnabled)
      delinkedEnabled: $(test_delinkedEnabled)
      combinedOfferEnabled: $(test_combinedOfferEnabled)
      cohtCapitalEnabled: $(test_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(test_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(test_sftpManagedGatewayUsername)
      sftpTraderHost: $(test_sftpTraderHost)
      sftpTraderUsername: $(test_sftpTraderUsername)
    pre_params:
      sftpManagedGatewayEnabled: $(pre_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(pre_sftpTraderEnabled)
      sfiEnabled: $(pre_sfiEnabled)
      sfiPilotEnabled: $(pre_sfiPilotEnabled)
      lumpSumsEnabled: $(pre_lumpSumsEnabled)
      csEnabled: $(pre_csEnabled)
      bpsEnabled: $(pre_bpsEnabled)
      esEnabled: $(pre_esEnabled)
      fcEnabled: $(pre_fcEnabled)
      impsEnabled: $(pre_impsEnabled)
      sfi23Enabled: $(pre_sfi23Enabled)
      dpsEnabled: $(pre_dpsEnabled)
      delinkedEnabled: $(pre_delinkedEnabled)
      combinedOfferEnabled: $(pre_combinedOfferEnabled)
      cohtCapitalEnabled: $(pre_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(pre_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(pre_sftpManagedGatewayUsername)
      sftpTraderHost: $(pre_sftpTraderHost)
      sftpTraderUsername: $(pre_sftpTraderUsername)
    prd_params:
      sftpManagedGatewayEnabled: $(prd_sftpManagedGatewayEnabled)
      sftpTraderEnabled: $(prd_sftpTraderEnabled)
      sfiEnabled: $(prd_sfiEnabled)
      sfiPilotEnabled: $(prd_sfiPilotEnabled)
      lumpSumsEnabled: $(prd_lumpSumsEnabled)
      csEnabled: $(prd_csEnabled)
      bpsEnabled: $(prd_bpsEnabled)
      esEnabled: $(prd_esEnabled)
      fcEnabled: $(prd_fcEnabled)
      impsEnabled: $(prd_impsEnabled)
      sfi23Enabled: $(prd_sfi23Enabled)
      dpsEnabled: $(prd_dpsEnabled)
      delinkedEnabled: $(prd_delinkedEnabled)
      combinedOfferEnabled: $(prd_combinedOfferEnabled)
      cohtCapitalEnabled: $(prd_cohtCapitalEnabled)
      sftpManagedGatewayHost: $(prd_sftpManagedGatewayHost)
      sftpManagedGatewayUsername: $(prd_sftpManagedGatewayUsername)
      sftpTraderHost: $(prd_sftpTraderHost)
      sftpTraderUsername: $(prd_sftpTraderUsername)
