# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-gateway-env-var
    pr_params:
      container.sftpManagedGatewayEnabled: $(pr_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(pr_sftpTraderEnabled)
      container.sfiEnabled: $(pr_sfiEnabled)
      container.sfiPilotEnabled: $(pr_sfiPilotEnabled)
      container.lumpSumsEnabled: $(pr_lumpSumsEnabled)
      container.csEnabled: $(pr_csEnabled)
      container.bpsEnabled: $(pr_bpsEnabled)
      container.esEnabled: $(pr_esEnabled)
      container.fcEnabled: $(pr_fcEnabled)
      container.impsEnabled: $(pr_impsEnabled)
      container.sfi23Enabled: $(pr_sfi23Enabled)
      container.dpsEnabled: $(pr_dpsEnabled)
      container.delinkedEnabled: $(pr_delinkedEnabled)
      container.combinedOfferEnabled: $(pr_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(pr_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(pr_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(pr_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(pr_sftpTraderHost)
      container.sftpTraderUsername: $(pr_sftpTraderUsername)
    snd2_params:
      container.sftpManagedGatewayEnabled: $(snd2_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(snd2_sftpTraderEnabled)
      container.sfiEnabled: $(snd2_sfiEnabled)
      container.sfiPilotEnabled: $(snd2_sfiPilotEnabled)
      container.lumpSumsEnabled: $(snd2_lumpSumsEnabled)
      container.csEnabled: $(snd2_csEnabled)
      container.bpsEnabled: $(snd2_bpsEnabled)
      container.esEnabled: $(snd2_esEnabled)
      container.fcEnabled: $(snd2_fcEnabled)
      container.impsEnabled: $(snd2_impsEnabled)
      container.sfi23Enabled: $(snd2_sfi23Enabled)
      container.dpsEnabled: $(snd2_dpsEnabled)
      container.delinkedEnabled: $(snd2_delinkedEnabled)
      container.combinedOfferEnabled: $(snd2_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(snd2_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(snd2_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(snd2_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(snd2_sftpTraderHost)
      container.sftpTraderUsername: $(snd2_sftpTraderUsername)
    dev_params:
      container.sftpManagedGatewayEnabled: $(dev_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(dev_sftpTraderEnabled)
      container.sfiEnabled: $(dev_sfiEnabled)
      container.sfiPilotEnabled: $(dev_sfiPilotEnabled)
      container.lumpSumsEnabled: $(dev_lumpSumsEnabled)
      container.csEnabled: $(dev_csEnabled)
      container.bpsEnabled: $(dev_bpsEnabled)
      container.esEnabled: $(dev_esEnabled)
      container.fcEnabled: $(dev_fcEnabled)
      container.impsEnabled: $(dev_impsEnabled)
      container.sfi23Enabled: $(dev_sfi23Enabled)
      container.dpsEnabled: $(dev_dpsEnabled)
      container.delinkedEnabled: $(dev_delinkedEnabled)
      container.combinedOfferEnabled: $(dev_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(dev_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(dev_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(dev_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(dev_sftpTraderHost)
      container.sftpTraderUsername: $(dev_sftpTraderUsername)
    test_params:
      container.sftpManagedGatewayEnabled: $(test_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(test_sftpTraderEnabled)
      container.sfiEnabled: $(test_sfiEnabled)
      container.sfiPilotEnabled: $(test_sfiPilotEnabled)
      container.lumpSumsEnabled: $(test_lumpSumsEnabled)
      container.csEnabled: $(test_csEnabled)
      container.bpsEnabled: $(test_bpsEnabled)
      container.esEnabled: $(test_esEnabled)
      container.fcEnabled: $(test_fcEnabled)
      container.impsEnabled: $(test_impsEnabled)
      container.sfi23Enabled: $(test_sfi23Enabled)
      container.dpsEnabled: $(test_dpsEnabled)
      container.delinkedEnabled: $(test_delinkedEnabled)
      container.combinedOfferEnabled: $(test_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(test_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(test_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(test_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(test_sftpTraderHost)
      container.sftpTraderUsername: $(test_sftpTraderUsername)
    pre_params:
      container.sftpManagedGatewayEnabled: $(pre_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(pre_sftpTraderEnabled)
      container.sfiEnabled: $(pre_sfiEnabled)
      container.sfiPilotEnabled: $(pre_sfiPilotEnabled)
      container.lumpSumsEnabled: $(pre_lumpSumsEnabled)
      container.csEnabled: $(pre_csEnabled)
      container.bpsEnabled: $(pre_bpsEnabled)
      container.esEnabled: $(pre_esEnabled)
      container.fcEnabled: $(pre_fcEnabled)
      container.impsEnabled: $(pre_impsEnabled)
      container.sfi23Enabled: $(pre_sfi23Enabled)
      container.dpsEnabled: $(pre_dpsEnabled)
      container.delinkedEnabled: $(pre_delinkedEnabled)
      container.combinedOfferEnabled: $(pre_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(pre_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(pre_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(pre_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(pre_sftpTraderHost)
      container.sftpTraderUsername: $(pre_sftpTraderUsername)
    prd_params:
      container.sftpManagedGatewayEnabled: $(prd_sftpManagedGatewayEnabled)
      container.sftpTraderEnabled: $(prd_sftpTraderEnabled)
      container.sfiEnabled: $(prd_sfiEnabled)
      container.sfiPilotEnabled: $(prd_sfiPilotEnabled)
      container.lumpSumsEnabled: $(prd_lumpSumsEnabled)
      container.csEnabled: $(prd_csEnabled)
      container.bpsEnabled: $(prd_bpsEnabled)
      container.esEnabled: $(prd_esEnabled)
      container.fcEnabled: $(prd_fcEnabled)
      container.impsEnabled: $(prd_impsEnabled)
      container.sfi23Enabled: $(prd_sfi23Enabled)
      container.dpsEnabled: $(prd_dpsEnabled)
      container.delinkedEnabled: $(prd_delinkedEnabled)
      container.combinedOfferEnabled: $(prd_combinedOfferEnabled)
      container.cohtCapitalEnabled: $(prd_cohtCapitalEnabled)
      container.sftpManagedGatewayHost: $(prd_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(prd_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(prd_sftpTraderHost)
      container.sftpTraderUsername: $(prd_sftpTraderUsername)