# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    failOnThreshold: low
    variableGroupName: ffc-pay-gateway-env-var
    pr_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['pr_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['pr_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['pr_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['pr_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['pr_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['pr_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['pr_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['pr_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['pr_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['pr_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['pr_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['pr_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['pr_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['pr_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['pr_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(pr_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(pr_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(pr_sftpTraderHost)
      container.sftpTraderUsername: $(pr_sftpTraderUsername)
    snd2_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['snd2_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['snd2_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['snd2_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['snd2_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['snd2_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['snd2_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['snd2_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['snd2_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['snd2_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['snd2_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['snd2_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['snd2_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['snd2_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['snd2_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['snd2_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(snd2_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(snd2_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(snd2_sftpTraderHost)
      container.sftpTraderUsername: $(snd2_sftpTraderUsername)
    dev_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['dev_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['dev_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['dev_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['dev_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['dev_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['dev_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['dev_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['dev_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['dev_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['dev_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['dev_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['dev_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['dev_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['dev_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['dev_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(dev_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(dev_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(dev_sftpTraderHost)
      container.sftpTraderUsername: $(dev_sftpTraderUsername)
    test_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['test_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['test_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['test_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['test_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['test_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['test_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['test_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['test_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['test_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['test_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['test_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['test_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['test_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['test_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['test_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(test_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(test_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(test_sftpTraderHost)
      container.sftpTraderUsername: $(test_sftpTraderUsername)
    pre_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['pre_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['pre_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['pre_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['pre_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['pre_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['pre_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['pre_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['pre_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['pre_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['pre_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['pre_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['pre_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['pre_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['pre_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['pre_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(pre_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(pre_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(pre_sftpTraderHost)
      container.sftpTraderUsername: $(pre_sftpTraderUsername)
    prd_params:
      container.sftpManagedGatewayEnabled: ${{ eq(variables['prd_sftpManagedGatewayEnabled'], 'true') }}
      container.sftpTraderEnabled: ${{ eq(variables['prd_sftpTraderEnabled'], 'true') }}
      container.sfiEnabled: ${{ eq(variables['prd_sfiEnabled'], 'true') }}
      container.sfiPilotEnabled: ${{ eq(variables['prd_sfiPilotEnabled'], 'true') }}
      container.lumpSumsEnabled: ${{ eq(variables['prd_lumpSumsEnabled'], 'true') }}
      container.csEnabled: ${{ eq(variables['prd_csEnabled'], 'true') }}
      container.bpsEnabled: ${{ eq(variables['prd_bpsEnabled'], 'true') }}
      container.esEnabled: ${{ eq(variables['prd_esEnabled'], 'true') }}
      container.fcEnabled: ${{ eq(variables['prd_fcEnabled'], 'true') }}
      container.impsEnabled: ${{ eq(variables['prd_impsEnabled'], 'true') }}
      container.sfi23Enabled: ${{ eq(variables['prd_sfi23Enabled'], 'true') }}
      container.dpsEnabled: ${{ eq(variables['prd_dpsEnabled'], 'true') }}
      container.delinkedEnabled: ${{ eq(variables['prd_delinkedEnabled'], 'true') }}
      container.combinedOfferEnabled: ${{ eq(variables['prd_combinedOfferEnabled'], 'true') }}
      container.cohtCapitalEnabled: ${{ eq(variables['prd_cohtCapitalEnabled'], 'true') }}
      container.sftpManagedGatewayHost: $(prd_sftpManagedGatewayHost)
      container.sftpManagedGatewayUsername: $(prd_sftpManagedGatewayUsername)
      container.sftpTraderHost: $(prd_sftpTraderHost)
      container.sftpTraderUsername: $(prd_sftpTraderUsername)
