services:
  ffc-pay-gateway:
    build:
      context: .
      target: production
    image: ffc-pay-gateway
    container_name: ffc-pay-gateway
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-gateway-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      SFTP_MANAGED_GATEWAY_HOST: ffc-pay-gateway-sftp
      SFTP_MANAGED_GATEWAY_USERNAME: ffc
      SFTP_MANAGED_GATEWAY_PASSWORD: password
      SFTP_CALLISTO_HOST: ffc-pay-gateway-sftp
      SFTP_CALLISTO_USERNAME: ffc
      SFTP_CALLISTO_PASSWORD: password
      SFI_DIRECTORY: local-directory
      SFI_PILOT_DIRECTORY: local-directory
      LUMP_SUMS_DIRECTORY: local-directory
      CS_DIRECTORY: local-directory
      BPS_DIRECTORY: local-directory
      ES_DIRECTORY: local-directory
      FC_DIRECTORY: local-directory
      IMPS_DIRECTORY: local-directory
      SFI23_DIRECTORY: local-directory

  ffc-pay-batch-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-batch-azurite

  ffc-pay-gateway-sftp:
    image: atmoz/sftp
