services:
  ffc-pay-gateway:
    build:
      context: .
      target: production
    image: ffc-pay-gateway
    container_name: ffc-pay-gateway
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-gateway-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      SFTP_MANAGED_GATEWAY_HOST: ffc-pay-gateway-sftp
      SFTP_MANAGED_GATEWAY_USERNAME: ffc
      SFTP_MANAGED_GATEWAY_PRIVATE_KEY: ${SFTP_MANAGED_GATEWAY_PRIVATE_KEY}
      SFTP_TRADER_HOST: ffc-pay-gateway-sftp
      SFTP_TRADER_USERNAME: ffc
      SFTP_TRADER_PRIVATE_KEY: ${SFTP_TRADER_PRIVATE_KEY}
      SFI_INBOUND_DIRECTORY: local-directory/inbound
      SFI_PILOT_INBOUND_DIRECTORY: local-directory/inbound
      LUMP_SUMS_INBOUND_DIRECTORY: local-directory/inbound
      CS_INBOUND_DIRECTORY: local-directory/inbound
      BPS_INBOUND_DIRECTORY: local-directory/inbound
      FDMR_INBOUND_DIRECTORY: local-directory/inbound
      ES_INBOUND_DIRECTORY: local-directory/inbound
      ES_OUTBOUND_DIRECTORY: local-directory/outbound
      FC_INBOUND_DIRECTORY: local-directory/inbound
      FC_OUTBOUND_DIRECTORY: local-directory/outbound
      IMPS_INBOUND_DIRECTORY: local-directory/inbound
      IMPS_OUTBOUND_DIRECTORY: local-directory/outbound
      SFI23_INBOUND_DIRECTORY: local-directory/inbound
      DPS_INBOUND_DIRECTORY: local-directory/inbound
      DPS_OUTBOUND_DIRECTORY: local-directory/outbound
      DELINKED_INBOUND_DIRECTORY: local-directory/inbound
      SFI_EXPANDED_INBOUND_DIRECTORY: local-directory/inbound
      IMPS_POLL_WINDOW_START: ${IMPS_POLL_WINDOW_START}
      IMPS_POLL_WINDOW_END: ${IMPS_POLL_WINDOW_END}
      IMPS_POLL_DAYS: ${IMPS_POLL_DAYS}
      DPS_POLL_WINDOW_START: ${DPS_POLL_WINDOW_START}
      DPS_POLL_WINDOW_END: ${DPS_POLL_WINDOW_END}
      DPS_POLL_DAYS: ${DPS_POLL_DAYS}

  ffc-pay-batch-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-batch-azurite

  ffc-pay-gateway-sftp:
    image: atmoz/sftp
