# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-pay-gateway:
    build:
      target: development
    image: ffc-pay-gateway-development
    container_name: ffc-pay-gateway-test
    depends_on:
      - ffc-pay-batch-azurite
      - ffc-pay-gateway-sftp
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-batch-azurite:10000/devstoreaccount1;
      SFTP_MANAGED_GATEWAY_PASSWORD: password
      SFTP_CALLISTO_PASSWORD: password

  ffc-pay-batch-azurite:
    labels:
      com.docker.compose.pay.role: test

  ffc-pay-gateway-sftp:
    command: ffc:password:::local-directory/inbound,local-directory/outbound
