{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-gateway.config-map") -}}
{{- define "ffc-pay-gateway.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  POLLING_INTERVAL: {{ quote .Values.container.pollingInterval }}
  POLLING_ACTIVE: {{ quote .Values.container.pollingActive }}
  SFTP_DEBUG: {{ quote .Values.container.sftpDebug }}
  SFTP_MANAGED_GATEWAY_HOST: {{ quote .Values.container.sftpManagedGatewayHost }}
  SFPT_MANAGED_GATEWAY_PORT: {{ quote .Values.container.sftpManagedGatewayPort }}
  SFTP_TRADER_HOST: {{ quote .Values.container.sftpTraderHost }}
  SFTP_TRADER_PORT: {{ quote .Values.container.sftpTraderPort }}
  IMPS_POLL_WINDOW_START: {{ quote .Values.container.impsPollWindowStart }}
  IMPS_POLL_WINDOW_END: {{ quote .Values.container.impsPollWindowEnd }}
  IMPS_POLL_DAYS: {{ quote .Values.container.impsPollDays }}
  DPS_POLL_WINDOW_START: {{ quote .Values.container.dpsPollWindowStart }}
  DPS_POLL_WINDOW_END: {{ quote .Values.container.dpsPollWindowEnd }}
  DPS_POLL_DAYS: {{ quote .Values.container.dpsPollDays }}
  {{- if and (.Values.environmentCode) (eq (.Values.environmentCode | toString ) "prd") }}
  SFI_INBOUND_DIRECTORY: {{ quote .Values.container.sfiInboundDirectory }}
  SFI_PILOT_INBOUND_DIRECTORY: {{ quote .Values.container.sfiPilotInboundDirectory }}
  LUMP_SUMS_INBOUND_DIRECTORY: {{ quote .Values.container.lumpSumsInboundDirectory }}
  CS_INBOUND_DIRECTORY: {{ quote .Values.container.csInboundDirectory }}
  BPS_INBOUND_DIRECTORY: {{ quote .Values.container.bpsInboundDirectory }}
  FDMR_INBOUND_DIRECTORY: {{ quote .Values.container.fdmrInboundDirectory }}
  ES_INBOUND_DIRECTORY: {{ quote .Values.container.esInboundDirectory }}
  ES_OUTBOUND_DIRECTORY: {{ quote .Values.container.esOutboundDirectory }}
  FC_INBOUND_DIRECTORY: {{ quote .Values.container.fcInboundDirectory }}
  FC_OUTBOUND_DIRECTORY: {{ quote .Values.container.fcOutboundDirectory }}
  SFI23_INBOUND_DIRECTORY: {{ quote .Values.container.sfi23InboundDirectory }}
  DELINKED_INBOUND_DIRECTORY: {{ quote .Values.container.delinkedInboundDirectory }}
  COMBINED_OFFER_INBOUND_DIRECTORY: {{ quote .Values.container.combinedOfferInboundDirectory }}
  COHT_CAPITAL_INBOUND_DIRECTORY: {{ quote .Values.container.cohtCapitalInboundDirectory }}
  {{ else }}
  SFI_INBOUND_DIRECTORY: {{ .Values.container.sfiInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  SFI_PILOT_INBOUND_DIRECTORY: {{ .Values.container.sfiPilotInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  LUMP_SUMS_INBOUND_DIRECTORY: {{ .Values.container.lumpSumsInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  CS_INBOUND_DIRECTORY: {{ .Values.container.csInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  BPS_INBOUND_DIRECTORY: {{ .Values.container.bpsInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  FDMR_INBOUND_DIRECTORY: {{ .Values.container.fdmrInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  ES_INBOUND_DIRECTORY: {{ .Values.container.esInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  ES_OUTBOUND_DIRECTORY: {{ .Values.container.esOutboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  FC_INBOUND_DIRECTORY: {{ .Values.container.fcInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  FC_OUTBOUND_DIRECTORY: {{ .Values.container.fcOutboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  SFI23_INBOUND_DIRECTORY: {{ .Values.container.sfi23InboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  DELINKED_INBOUND_DIRECTORY: {{ .Values.container.delinkedInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  COMBINED_OFFER_INBOUND_DIRECTORY: {{ quote .Values.container.combinedOfferInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  COHT_CAPITAL_INBOUND_DIRECTORY: {{ quote .Values.container.cohtCapitalInboundDirectory | replace "cap_prod_data" "cap_test_data" }}
  {{- end }}
  IMPS_INBOUND_DIRECTORY: {{ quote .Values.container.impsInboundDirectory }}
  IMPS_OUTBOUND_DIRECTORY: {{ quote .Values.container.impsOutboundDirectory }}
  DPS_INBOUND_DIRECTORY: {{ quote .Values.container.dpsInboundDirectory }}
  DPS_OUTBOUND_DIRECTORY: {{ quote .Values.container.dpsOutboundDirectory }}
  SFTP_MANAGED_GATEWAY_ENABLED: {{ quote .Values.container.sftpManagedGatewayEnabled }}
  SFTP_TRADER_ENABLED: {{ quote .Values.container.sftpTraderEnabled }}
  SFI_ENABLED: {{ quote .Values.container.sfiEnabled }}
  SFI_PILOT_ENABLED: {{ quote .Values.container.sfiPilotEnabled }}
  LUMP_SUMS_ENABLED: {{ quote .Values.container.lumpSumsEnabled }}
  CS_ENABLED: {{ quote .Values.container.csEnabled }}
  BPS_ENABLED: {{ quote .Values.container.bpsEnabled }}
  ES_ENABLED: {{ quote .Values.container.esEnabled }}
  FC_ENABLED: {{ quote .Values.container.fcEnabled }}
  IMPS_ENABLED: {{ quote .Values.container.impsEnabled }}
  SFI23_ENABLED: {{ quote .Values.container.sfi23Enabled }}
  DPS_ENABLED: {{ quote .Values.container.dpsEnabled }}
  DELINKED_ENABLED: {{ quote .Values.container.delinkedEnabled }}
  COMBINED_OFFER_ENABLED: {{ quote .Values.container.combinedOfferEnabled }}
  COHT_CAPITAL_ENABLED: {{ quote .Values.container.cohtCapitalEnabled }}
{{- end -}}
