{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-gateway.container-secret") -}}
{{- define "ffc-pay-gateway.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  SFTP_CALLISTO_USERNAME: {{ quote .Values.container.sftpCallistoUsername }}
  {{- if .Values.container.sftpCallistoPassword }}
  SFTP_CALLISTO_PASSWORD: {{ quote .Values.container.sftpCallistoPassword }}
  {{- end }}
  {{- if .Values.container.sftpCallistoPrivateKey }}
  SFTP_CALLISTO_PRIVATE_KEY: {{ quote .Values.container.sftpCallistoPrivateKey }}
  {{- end }}
  SFTP_MANAGED_GATEWAY_USERNAME: {{ quote .Values.container.sftpManagedGatewayUsername }}
  {{- if .Values.container.sftpManagedGatewayPassword }}
  SFTP_MANAGED_GATEWAY_PASSWORD: {{ quote .Values.container.sftpManagedGatewayPassword }}
  {{- end }}
  {{- if .Values.container.sftpManagedGatewayPrivateKey }}
  SFTP_MANAGED_GATEWAY_PRIVATE_KEY: {{ quote .Values.container.sftpManagedGatewayPrivateKey }}
  {{- end }}
{{- end -}}
