---
environment: production
environmentCode: dev
container:
  sftpDebug: true
  sftpManagedGatewayEnabled: false
  sftpTraderEnabled: false
  azureStorageAccountName: devffcpayst1001
  sfiEnabled: true
  sfiPilotEnabled: true
  lumpSumsEnabled: true
  csEnabled: true
  bpsEnabled: true
  esEnabled: true
  fcEnabled: true
  impsEnabled: true
  sfi23Enabled: true
  dpsEnabled: false
  delinkedEnabled: true
  combinedOfferEnabled: true
  cohtCapitalEnabled: true

secretProviderClass:
  azure:
    keyvaultName: DEVFFCINFKV1001
    objects: # reading the secret from Azure Key Vault
      - objectName: devtest-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: devtest-ffc-pay-sftpManagedGatewayHost # to be created
        objectType: secret
      - objectName: devtest-ffc-pay-sftpTraderHost # to be created
        objectType: secret
      - objectName: devtest-ffc-pay-sftpManagedGatewayUsername # to be created
        objectType: secret
      - objectName: devtest-ffc-pay-sftpTraderUsername # to be created
        objectType: secret
      - objectName: ffc-pay-callisto-password
        objectType: secret
      - objectName: ffc-pay-managed-gateway-key
        objectType: secret

  secretObjects: # creating a kubernetes secret from the Azure Key Vault secrets
    - secretName: ffc-pay-gateway
      type: Opaque
      data:
        - objectName: devtest-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: devtest-ffc-pay-sftpManagedGatewayHost
          key: SFTP_MANAGED_GATEWAY_HOST
        - objectName: devtest-ffc-pay-sftpTraderHost
          key: SFTP_TRADER_HOST
        - objectName: devtest-ffc-pay-sftpManagedGatewayUsername
          key: SFTP_MANAGED_GATEWAY_USERNAME
        - objectName: devtest-ffc-pay-sftpTraderUsername
          key: SFTP_TRADER_USERNAME
        - objectName: ffc-pay-callisto-password
          key: SFTP_TRADER_PASSWORD
        - objectName: ffc-pay-managed-gateway-key
          key: SFTP_MANAGED_GATEWAY_PRIVATE_KEY