---
environment: production
environmentCode: prd
container:
  sftpManagedGatewayEnabled: true
  sftpTraderEnabled: true
  azureStorageAccountName: prdffcpayst1001
  sfiEnabled: true
  sfiPilotEnabled: true
  lumpSumsEnabled: true
  csEnabled: true
  bpsEnabled: true
  esEnabled: true
  fcEnabled: true
  impsEnabled: true
  sfi23Enabled: true
  dpsEnabled: true
  delinkedEnabled: true
  combinedOfferEnabled: true
  cohtCapitalEnabled: false

secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects: # reading the secret from Azure Key Vault
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret
      - objectName: prd-ffc-pay-sftpManagedGatewayHost # to be created
        objectType: secret
      - objectName: prd-ffc-pay-sftpTraderHost # to be created
        objectType: secret
      - objectName: prd-ffc-pay-sftpManagedGatewayUsername # to be created
        objectType: secret
      - objectName: prd-ffc-pay-sftpTraderUsername # to be created
        objectType: secret
      - objectName: ffc-pay-callisto-password
        objectType: secret
      - objectName: ffc-pay-managed-gateway-private-key
        objectType: secret

  secretObjects: # creating a kubernetes secret from the Azure Key Vault secrets
    - secretName: ffc-pay-gateway
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-ffc-pay-sftpManagedGatewayHost
          key: SFTP_MANAGED_GATEWAY_HOST
        - objectName: prd-ffc-pay-sftpTraderHost
          key: SFTP_TRADER_HOST
        - objectName: prd-ffc-pay-sftpManagedGatewayUsername
          key: SFTP_MANAGED_GATEWAY_USERNAME
        - objectName: prd-ffc-pay-sftpTraderUsername
          key: SFTP_TRADER_USERNAME
        - objectName: ffc-pay-callisto-password
          key: SFTP_TRADER_PASSWORD
        - objectName: ffc-pay-managed-gateway-private-key
          key: SFTP_MANAGED_GATEWAY_PRIVATE_KEY