#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-pay$ --format={{.Name}})" ]; then
  echo "Creating ffc-pay Docker network"
  docker network create ffc-pay
fi

if [ -n "$(docker container ls --filter label=com.docker.compose.pay.role=ffc-pay-batch-azurite --format={{.ID}})" ]; then
  echo "Azurite container already exists, skipping creation"
  args="--scale ffc-pay-batch-azurite=0"
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

mkdir -p .ssh

if [ ! -f .ssh/ssh_host_ed25519_key ]; then
  echo "Generating ed25519 SSH keys"
  ssh-keygen -t ed25519 -f .ssh/ssh_host_ed25519_key < /dev/null
fi

if [ ! -f .ssh/ssh_host_rsa_key ]; then
  echo "Generating rsa SSH keys"
  ssh-keygen -t rsa -b 4096 -f .ssh/ssh_host_rsa_key < /dev/null
fi

export SFTP_MANAGED_GATEWAY_PRIVATE_KEY=$(cat .ssh/ssh_host_rsa_key)
export SFTP_CALLISTO_PRIVATE_KEY=$(cat .ssh/ssh_host_rsa_key)

docker compose down

docker compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $args $@
