environment: development
environmentCode:
name: ffc-pay-gateway
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-gateway

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-gateway-config-map

containerSecret:
  name: ffc-pay-gateway-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 60m
  limitMemory: 200Mi
  limitCpu: 200m
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  pollingInterval: 10000
  pollingActive: true
  sftpManagedGatewayHost: managed-gateway
  sftpManagedGatewayPort: 22
  sftpManagedGatewayUsername: ffc
  sftpManagedGatewayPassword:
  sftpManagedGatewayPrivateKey:
  sftpCallistoHost: callisto
  sftpCallistoPort: 22
  sftpCallistoUsername: ffc
  sftpCallistoPassword:
  sftpCallistoPrivateKey:
  sfiInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  sfiPilotInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  lumpSumsInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  csInboundDirectory: /opt/cap_prod_data/DAX/out/int_716
  bpsInboundDirectory: /opt/cap_prod_data/DAX/out/int_539
  esInboundDirectory: /opt/cap_prod_data/genesis/in/int_072
  esOutboundDirectory: /opt/cap_prod_data/genesis/out/int_073
  fcInboundDirectory: /opt/cap_prod_data/glos/in/int_230
  fcOutboundDirectory: /opt/cap_prod_data/glos/out/int_231
  impsInboundDirectory: /app/DAX_interface/CFI/outbound
  impsOutboundDirectory: /app/DAX_interface/CFI/inbound
  sfi23InboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  dpsInboundDirectory: /app/DAX_interface/DPS/outbound
  dpsOutboundDirectory: /app/DAX_interface/DAX/inbound
  sftpDebug: false
  sftpManagedGatewayEnabled: true
  sftpCallistoEnabled: true
  sfiEnabled: true
  sfiPilotEnabled: true
  lumpSumsEnabled: true
  csEnabled: true
  bpsEnabled: true
  esEnabled: true
  fcEnabled: true
  impsEnabled: true
  sfi23Enabled: true
  dpsEnabled: true

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
