environment: development
environmentCode:
name: ffc-pay-gateway
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-gateway

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-gateway-config-map

containerSecret:
  name: ffc-pay-gateway-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 60m
  limitMemory: 200Mi
  limitCpu: 200m
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  pollingInterval: 10000
  pollingActive: true
  sftpManagedGatewayHost:
  sftpManagedGatewayPort: 22
  sftpManagedGatewayUsername:
  sftpManagedGatewayPassword:
  sftpCallistoHost:
  sftpCallistoPort: 22
  sftpCallistoUsername:
  sftpCallistoPassword:
  sfiInboundDirectory:
  sfiPilotInboundDirectory:
  lumpSumsInboundDirectory:
  csInboundDirectory:
  bpsInboundDirectory:
  esInboundDirectory:
  esOutboundDirectory:
  fcInboundDirectory:
  fcOutboundDirectory:
  impsInboundDirectory:
  impsOutboundDirectory:
  sfi23InboundDirectory:
  sfiEnabled: true
  sfiPilotEnabled: true
  lumpSumsEnabled: true
  csEnabled: true
  bpsEnabled: true
  esEnabled: true
  fcEnabled: true
  impsEnabled: true
  sfi23Enabled: true

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
