environment: development
environmentCode:
name: ffc-pay-gateway
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-gateway

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-gateway-config-map

containerSecret:
  name: ffc-pay-gateway-container-secret
  type: Opaque

deployment:
  priorityClassName: high

container:
  requestMemory: 100Mi
  requestCpu: 60m
  limitMemory: 200Mi
  limitCpu: 200m
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  pollingInterval: 10000
  pollingActive: true
  sftpManagedGatewayHost: managed-gateway
  sftpManagedGatewayPort: 22
  sftpManagedGatewayUsername: ffc
  sftpManagedGatewayPassword:
  sftpManagedGatewayPrivateKey:
  sftpTraderHost: trader
  sftpTraderPort: 22
  sftpTraderUsername: ffc
  sftpTraderPassword:
  sftpTraderPrivateKey:
  sfiInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  sfiPilotInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  lumpSumsInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  csInboundDirectory: /opt/cap_prod_data/DAX/out/int_716
  bpsInboundDirectory: /opt/cap_prod_data/DAX/out/int_539
  esInboundDirectory: /opt/cap_prod_data/genesis/in/int_073
  esOutboundDirectory: /opt/cap_prod_data/genesis/out/int_072
  fdmrInboundDirectory: /opt/cap_prod_data/DAX/out/int_539
  fcInboundDirectory: /opt/cap_prod_data/glos/in/int_230
  fcOutboundDirectory: /opt/cap_prod_data/glos/out/int_231
  impsInboundDirectory: D:\app\DAX_interface\CFI\outbound
  impsOutboundDirectory: D:\app\DAX_interface\CFI\inbound
  sfi23InboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  dpsInboundDirectory: D:\app\DAX_interface\DPS\outbound
  dpsOutboundDirectory: D:\app\DAX_interface\DPS\inbound
  delinkedInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  sfiExpandedInboundDirectory: /opt/cap_prod_data/DAX/out/Int_725
  sftpDebug: false
  sftpManagedGatewayEnabled: true
  sftpTraderEnabled: true
  sfiEnabled: true
  sfiPilotEnabled: true
  lumpSumsEnabled: true
  csEnabled: true
  bpsEnabled: true
  fdmrEnabled: false
  esEnabled: true
  fcEnabled: true
  impsEnabled: true
  sfi23Enabled: true
  dpsEnabled: true
  delinkedEnabled: true
  sfiExpandedEnabled: true
  impsPollWindowStart: "00:00"
  impsPollWindowEnd: "23:59"
  impsPollDays: "Sun,Mon,Tue,Wed,Thu,Fri,Sat"
  dpsPollWindowStart: "23:59"
  dpsPollWindowEnd: "18:00"
  dpsPollDays: "Sun,Mon,Tue,Wed,Thu,Fri,Sat"

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
