name: Bump NPM Version on PR open

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened  # This will trigger the workflow when the PR is reopened

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Configure Git for signed commits
        run: |
          echo "$ACTIONS_PRIVATE_KEY" | gpg --batch --import
          git config user.name "GitHub Actions Bot"
          git config user.email "samplackett@users.noreply.github.com"
          git config commit.gpgsign true
          git config gpg.format ssh
          git config user.signingkey "$ACTIONS_PRIVATE_KEY"

        env:
          ACTIONS_PRIVATE_KEY: ${{ secrets.ACTIONS_PRIVATE_KEY }}

      - name: Bump NPM version (patch)
        run: npm version patch

      - name: Commit and push version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit --amend --no-edit --gpg-sign
          git push origin HEAD:${{ github.head_ref }} --follow-tags
